[package]
name = "sudoku-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
itertools = "0.10"
crossbeam = "0.8"
num_cpus = "1.13"
log = "0.4"
env_logger = "0.9"
